version: "3.9"

services:
  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    container_name: agentic-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
      - OTLP_ENDPOINT=http://jaeger:4317
    volumes:
      - ./data/chroma:/app/data/chroma
      - ./brain4:/app/brain4
      - ./reports/pdf:/app/reports/pdf
      - ./model_cache:/root/.cache

    depends_on:
      - redis
      - jaeger
      - postgres
    restart: unless-stopped


  # Jaeger for Obervability and Latency
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
    environment:
      - COLLECTOR_OTLP_ENABLED=true     
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: agentic-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    restart: unless-stopped

  postgres:
    image: postgres:17

    container_name: agentic_saad

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: agentic_ai_saas
    
    ports:
      - "5433:5432"
    
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data:



