from nt import mkdir
from pathlib import Path
from datetime import datetime
from sqlite3.dbapi2 import Timestamp
import markdown
import os

class PDFGenerator:
    """Converts Markdown Reports to Professional PDFs"""


    def __init__(self, output_dir: str = "./reports/pdf"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents = True, exist_ok = True)
    

    def markdown_to_pdf(self, markdown_content: str, task_id: str =None, task_type: str =None, filename:str =None) ->str:
        """Convers Markdown to PDF
        
        Return: Path to PDF generated Path"""

        if filename:
            base_name = filename
        elif task_id and task_type:
            base_name = f"{task_id}_{task_type}"
        elif task_id:
            base_name = task_id
        else:
            base_name = "report"

        try:

            from weasyprint import HTML, CSS

            ### Convert markdown to html

            html_content = markdown.markdown(
                markdown_content,
                extensions = ['tables', 'fenced_code', 'nl2br']
            )


            ## ADD Professional Styling

            styled_html = f"""
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="UTF-8">
                <style>
                    body {{
                        font-family: 'Segoe UI', Arial, sans-serif;
                        line-height: 1.6;
                        color: #333;
                        max-width: 800px;
                        margin: 40px auto;
                        padding: 20px;
                    }}
                    h1 {{
                        color: #2563eb;
                        border-bottom: 3px solid #2563eb;
                        padding-bottom: 10px;
                    }}
                    h2 {{
                        color: #1e40af;
                        margin-top: 30px;
                    }}
                    table {{
                        border-collapse: collapse;
                        width: 100%;
                        margin: 20px 0;
                    }}
                    th, td {{
                        border: 1px solid #ddd;
                        padding: 12px;
                        text-align: left;
                    }}
                    th {{
                        background-color: #2563eb;
                        color: white;
                    }}
                    tr:nth-child(even) {{
                        background-color: #f9fafb;
                    }}
                    .footer {{
                        margin-top: 50px;
                        padding-top: 20px;
                        border-top: 1px solid #ddd;
                        color: #666;
                        font-size: 12px;
                    }}
                </style>
            </head>
            <body>
                {html_content}
                <div class="footer">
                    <p>Generated by Autonomous AI Agent</p>
                    <p>Task ID: {task_id}</p>
                    <p>Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
                </div>
            </body>
            </html>"""


            ## Generate PDF

            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            pdf_filename = f"{base_name}_{timestamp}.pdf"
            pdf_path = self.output_dir / pdf_filename 


            HTML(string = styled_html).write_pdf(pdf_path)

            print(f" PDF Generated: {pdf_path}")
            return str(pdf_path)
        
        except ImportError:
            print(" weasyprint is not installed: pip install weasyprint")
            return self._fallback_pdf(markdown_content, base_name)
        
        except Exception as e:
            print(f"Failed to Generate PDF {e}")
            return None

    def _fallback_pdf(self, content: str, base_name:str) ->str:
        """
        FALLBACK: Save .txt if PDF Generation fails
        """

        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        txt_filename = f"{base_name}_{timestamp}.txt"
        txt_path = self.output_dir / txt_filename

        with open(txt_path, "w", encoding= 'utf-8') as f:
            f.write(content)
        
        print(f"Saved as TXT (PDF Unvailable): {txt_path} ")
        return str(txt_path)

        