"""Email Agent - Sends final reports"""

from typing import List, Dict, Any
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import  MIMEApplication


class EmailAgent:
    def __init__(self, smtp_config: Dict[str, Any]):
        self.smtp_config = smtp_config

    def send_report(self, user_email: str, report_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Sends final report via email
        """
        try:
            msg = MIMEMultipart()
            msg['From'] = self.smtp_config['from_email']
            msg['TO'] = user_email
            msg['subject'] = f"Your job match report {report_data.get('timestamp', 'Today')}"


            ### HTML Body

            html_body = self._generate_email_html(report_data)
            msg.attach(MIMETEXT(html_body, 'html'))


            ## attach PDF
            if report_data.get("pdf_path"):
                with open(report_data, ["pdf_path"] , 'rb') as f:
                    pdf_attachment = MIMEApplication(f.read(), _subtype="pdf")
                    pdf_attachment.add_header('content-Disposition','attachment', filename ='job_report_pdf')

                    msg.attach(pdf_attachment)

            
            ## Send email

            with smtplib.SMTP(self.smtp_config['smtp_server'],
                   self.smtp_config['smtp_port']) as server:
              server.starttls()

              server.login(self.smtp_config['username'], self.smtp_config['password'])
              server.send_message(msg)


            return {"status": "sent", "recipent": "user_email"}

        except Exception as e:
            return {"status": "failed", "error": str(e)}
    
    def _generate_email_html(self, report_data: Dict[str, Any]) ->str:
        """Generate Professional HTML Report"""
        jobs = report_data.get("matched_jobs", [])

        html = f"""
        <html>
        <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
            <h2 style="color: #2c3e50;">Your Personalized Job Match Report</h2>
            <p>We found {len(jobs)} great opportunities matching your profile!</p>
            
            <h3>Top Matches:</h3>
        """
        
        for i, job in enumerate(jobs[:5], 1):
            html += f"""
            <div style="background: #f8f9fa; padding: 15px; margin: 10px 0; border-left: 4px solid #007bff;">
                <h4 style="margin: 0 0 10px 0;">{i}. {job.get('title', 'N/A')}</h4>
                <p style="margin: 5px 0;"><strong>Company:</strong> {job.get('company', 'N/A')}</p>
                <p style="margin: 5px 0;"><strong>Location:</strong> {job.get('location', 'N/A')}</p>
                <p style="margin: 5px 0;"><strong>Match Score:</strong> {job.get('match_percentage', 0):.1f}%</p>
                <a href="{job.get('url', '#')}" style="color: #007bff; text-decoration: none;">View Job →</a>
            </div>
            """
        
        html += """
            <p style="margin-top: 20px;">Full detailed report is attached as PDF.</p>
            <p style="color: #666; font-size: 12px;">This report was generated by your AI-powered job matching system.</p>
        </body>
        </html>
        """

        return html
        





